config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  sessions: "users/sessions"
  }

  root "home#index"

  get "/catalog", to: "catalog#index"
  resources :products, only: [:show] do
    resources :reviews, only: [:create]
  end
  resource :profile, only: [:show]
  resource :checkout, only: [:show, :create]
  resources :orders, only: [:index, :show]
  resources :categories, only: [:index, :show]
  resources :collections, only: [:index, :show]

  resource :cart, only: [:show] do
  post "add/:product_id", to: "cart_items#create", as: :add_item
  patch "update/:id", to: "cart_items#update", as: :update_item
  delete "remove/:id", to: "cart_items#destroy", as: :remove_item
end

namespace :admin do
  root to: "dashboard#show"
  resources :categories
  resources :collections
  resources :products
  resources :reviews, only: [:index, :destroy]
  resources :orders, only: [:index, :show, :update]

end
end

app/models/collection.rb
class Collection < ApplicationRecord
  has_many :product_collections, dependent: :destroy
  has_many :products, through: :product_collections
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/collections_controller.rb
class Admin::CollectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin!
  before_action :set_collection, only: %i[edit update destroy]

  def index
    @collections = Collection.includes(:products)
  end

  def new
    @collection = Collection.new
    @products = Product.all
  end

  def create
    @collection = Collection.new(collection_params)

    if @collection.save
      redirect_to admin_collections_path, notice: "Колекцію створено"
    else
      @products = Product.all
      render :new
    end
  end

  def edit
    @products = Product.all
  end

  def update
    if @collection.update(collection_params)
      redirect_to admin_collections_path, notice: "Колекцію оновлено"
    else
      @products = Product.all
      render :edit
    end
  end

  def destroy
    @collection.destroy
    redirect_to admin_collections_path, notice: "Колекцію видалено"
  end

  private

  def set_collection
    @collection = Collection.find(params[:id])
  end

  def collection_params
    params.require(:collection)
          .permit(:name, :description, :photo, product_ids: [])
  end

  def require_admin!
    redirect_to root_path unless current_user.role == "manager"
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  def index
    @collections = Collection
      .with_attached_photo
      .order(:name)
  end

   def show
    @collection = Collection.find(params[:id])

    @products = Product
      .joins(:collections)
      .where(collections: { id: @collection.id }, active: true)
      .includes(:reviews, images_attachments: :blob)
      .distinct
      .page(params[:page])
      .per(18)
  end
end

app/views/collections/_card.html.erb
<div class="category-card">

  <%= link_to collection_path(collection), class: "block" do %>

    <div class="aspect-square w-full mb-4 overflow-hidden">
      <% if collection.photo.attached? %>
        <%= image_tag collection.photo,
          class: "w-full h-full object-cover" %>
      <% else %>
        <div class="w-full h-full bg-gray-100"></div>
      <% end %>
    </div>

    <h3 class="text-sm mb-4 text-center hover:underline">
      <%= collection.name %>
    </h3>

  <% end %>

  <%= link_to "Перейти",
      collection_path(collection),
      class: "primary-button w-full text-center block" %>

</div>

app/views/collections/index.html.erb
<section class="py-12">
  <div class="container">

    <h1 class="text-center text-xl mb-10">
      Усі колекції
    </h1>

    <div
      class="grid gap-6 justify-center
             grid-cols-1
             sm:grid-cols-2
             lg:grid-cols-4"
    >
      <% @collections.each do |collection| %>
        <div class="category-card">

          <div class="aspect-square w-full mb-4 overflow-hidden">
            <% if collection.photo.attached? %>
              <%= image_tag collection.photo,
                class: "w-full h-full object-cover" %>
            <% else %>
              <div class="w-full h-full bg-gray-100"></div>
            <% end %>
          </div>

          <h3 class="text-sm mb-4 text-center">
            <%= collection.name %>
          </h3>

          <%= link_to "Перейти",
    collection_path(collection),
    class: "primary-button w-full text-center" %>

        </div>
      <% end %>
    </div>

  </div>
</section>

app/views/collections/show.html.erb
<section class="py-12">
  <div class="container">

    <h1 class="text-center text-xl mb-8">
      <%= @collection.name %>
    </h1>

    <% if @products.any? %>
      <div
        class="grid gap-6 justify-center
               grid-cols-1
               sm:grid-cols-2
               lg:grid-cols-4"
      >
        <% @products.each do |product| %>
          <%= render "products/card", product: product %>
        <% end %>
      </div>

      <div class="flex justify-center mt-10">
          <%= paginate @products, theme: 'custom' %>
      </div>
    <% else %>
      <p class="text-center text-gray-500">
        У цій колекції поки немає товарів
      </p>
    <% end %>

  </div>
</section>